name: Android APK Build v2

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install required SDK components
      run: |
        sdkmanager "platforms;android-33" "build-tools;33.0.2" "platform-tools"
        sdkmanager --licenses
      
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '8.0'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Generate Gradle Wrapper
      run: |
        cd android
        gradle wrapper --gradle-version 8.0
        
    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew
      
    - name: Check Gradle wrapper
      run: |
        cd android
        ls -la gradlew
        ls -la gradle/wrapper/
        ./gradlew --version
        
    - name: Clean project
      run: |
        cd android
        ./gradlew clean --stacktrace --info
        
    - name: List Android SDK components
      run: |
        sdkmanager --list | head -20
        
    - name: Check project structure
      run: |
        cd android
        find . -name "*.gradle" -type f
        cat app/build.gradle | head -20
        
    - name: Build debug APK
      run: |
        cd android
        ./gradlew assembleDebug --stacktrace --info --debug --scan
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: gps-tracker-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30 